### ISSUE TITLE
Asset Definition File Not Indexed

### ISSUE THREAD

**Issue by oleganza** [OpenAssets/open-assets-protocol#10]
Hey,

I'm embedding "u=http://example.com/xyz" URL (without TLS) into metadata field in the marker, it returns this JSON:

```
{"asset_ids":["A-REDACTED"],"name_short":"REDACTED","name":"REDACTED","issuer":"REDACTED","type":"Stock","divisibility":0,"version":"1.0"}
```

And this is not indexed by Coinprism. Could it be that certain HTTP headers are expected, or some fields that are missing are actually required? I double-checked that Asset IDs match (there's no P2SH-based definition). Transaction is confirmed and visible on Coinprism, but asset name is not.

**Comment by Flavien** [comment]
Send me a private message with the asset ID, I can check what the actual error was.
