### ISSUE TITLE
What does mean "OA protocol prevents asset loss"?

### ISSUE THREAD

**Issue by oleganza** [OpenAssets/open-assets-protocol#11]
Here:
http://blog.coinprism.com/comparison-coinprism-counterparty-mastercoin/

I've noticed that CoinSpark says that all excessive assets are automatically sent to the last non-OP_RETURN output as change. I couldn't find anything like that in OpenAssets doc while that chart mentions something like that.

My personal opinion: we don't need that kind of babysitting that makes asset tracking only more complicated. However, I'd like to clarify that.

**Comment by Flavien** [comment]
Asset loss is prevented at the user interface level using the "open asset address format" (as we discussed in https://github.com/OpenAssets/open-assets-protocol/issues/7).

If you try to send colored coins to a regular address, you should receive an error from the wallet/API you are using, preventing you from sending colored coins to a wallet that might misspend them.

We don't use special rules like Coinspark, as like you said, it makes asset tracking much more expensive.
