### ISSUE TITLE
Can the marker contain more than 1 pushdata item?

### ISSUE THREAD

**Issue by oleganza** [OpenAssets/open-assets-protocol#8]
I'm currently implementing the protocol and accepting multi-pushdata OP_RETURN scripts, but only taking the first pushdata ignoring the rest. Should we enforce 1 pushdata only? Should we also enforce canonical pushdata opcode (that is, the most compact for the given data length)? I don't see much value in being liberal here. Especially since we might extend the protocol and desire to have some options being unused to take advantage of.

**Comment by Flavien** [comment]
On multiple pushdata: I think we might just take the first valid data (with valid marker payload), same as in case of multiple OP_RETURN:

> If multiple valid marker outputs exist in the same transaction, the first one is used and the other ones are considered as regular outputs

On non-canonical pushdata opcode: Any pushdata opcode is valid. Non-canonical pushdata will be non-standard soon anyway.

**Comment by oleganza** [comment]
Makes sense, thanks.
