### ISSUE TITLE
Updating Asset Definition Pointer without issuance or transfers

### ISSUE THREAD

**Issue by oleganza** [OpenAssets/open-assets-protocol#9]
According to the spec, I don't need to issue or transfer any assets to update the AD pointer. So do I understand correctly, that this is legal:

1. Send some satoshis to issuance address.
2. Spend that output in a transaction with an OA marker containing new definition pointer.

All inputs and outputs will be uncolored (no transfers and no new assets issued), but the second transaction will nonetheless be valid OA transaction and therefore will be parsed by a compliant client to get the latest Asset Definition from it?

**Comment by Flavien** [comment]
Yes this is correct. You can have a simple transaction that is not issuing or transferring anything, for the purpose of just updating the asset definition URL.

For example, in Coinprism, if you try to issue zero units of an asset, it will create such transaction (with only a marker output and uncolored Bitcoin change output).
